import { CustomConnectButton } from '@/components/custom-connect-button';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="min-h-screen py-16 flex-1 flex flex-col justify-center items-center">
        <CustomConnectButton />

        <h1 className="my-12 leading-none text-4xl text-center font-bold">
          Welcome to{' '}
          <a href="" className="text-blue-600 hover:underline focus:underline active:underline">
            RainbowKit
          </a>{' '}
          +{' '}
          <a href="" className="text-blue-600 hover:underline focus:underline active:underline">
            wagmi
          </a>{' '}
          +{' '}
          <a
            href="https://nextjs.org"
            className="text-blue-600 hover:underline focus:underline active:underline"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-0 mb-8 leading-relaxed text-3xl text-center">
          Get started by editing <code className="text-blue-600">pages/index.tsx</code>
        </p>

        <div className="flex items-center justify-center flex-wrap flex-col max-w-[800px] sm:w-full sm:flex-row text-lg">
          <a
            className="m-4 p-6 text-left h-full text-inherit no-underline border border-gray-200 rounded-lg transition-colors duration-150 ease-in-out max-w-xs hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:text-blue-600 active:border-blue-600"
            href="https://rainbowkit.com"
          >
            <h2 className="mb-2 font-bold">RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a
            className="m-4 p-6 text-left text-inherit no-underline border border-gray-200 rounded-lg transition-colors duration-150 ease-in-out max-w-xs hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:text-blue-600 active:border-blue-600"
            href="https://wagmi.sh"
          >
            <h2 className="mb-2 font-bold">wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className="m-4 p-6 text-left text-inherit no-underline border border-gray-200 rounded-lg transition-colors duration-150 ease-in-out max-w-xs hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:text-blue-600 active:border-blue-600"
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2 className="mb-2 font-bold">RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a
            className="m-4 p-6 text-left text-inherit no-underline border border-gray-200 rounded-lg transition-colors duration-150 ease-in-out max-w-xs hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:text-blue-600 active:border-blue-600"
            href="https://nextjs.org/docs"
          >
            <h2 className="mb-2 font-bold">Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className="m-4 p-6 text-left text-inherit no-underline border border-gray-200 rounded-lg transition-colors duration-150 ease-in-out max-w-xs hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:text-blue-600 active:border-blue-600"
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2 className="mb-2 font-bold">Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className="m-4 p-6 text-left text-inherit no-underline border border-gray-200 rounded-lg transition-colors duration-150 ease-in-out max-w-xs hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:text-blue-600 active:border-blue-600"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2 className="mb-2 font-bold">Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className="flex flex-1 py-8 border-t border-gray-200 justify-center items-center">
        <a
          href="https://rainbow.me"
          rel="noopener noreferrer"
          target="_blank"
          className="flex justify-center items-center flex-grow"
        >
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
